# Generated by Django 3.2 on 2021-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_register_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='deliveryaddress',
        ),
    ]
