# Generated by Django 3.2 on 2021-06-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_rename_deliveryaddress_register_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='delivery_address',
            new_name='delivery_Address',
        ),
    ]
