# Generated by Django 3.2 on 2021-06-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_rename_delivery_address_register_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
    ]
